// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "nuxt-primevue",
    "@nuxtjs/tailwindcss",
    "@vueuse/nuxt",
    "nuxt-icon",
    "@nuxtjs/supabase",
    "@nuxt/content",
  ],
  ssr: false,
  app: {
    head: {
      link: [
        {
          id: "theme-link",
          rel: "stylesheet",
          href: process.env.NUXT_BASE_URL + "aura-dark-cyan/theme.css",
        },
      ],
    },
  },
  content: {
    highlight: {
      theme: "dracula",
      langs: [
        "c",
        "cpp",
        "java",
        "go",
        "groovy",
        "haskell",
        "html",
        "javascript",
        "json",
        "json5",
        "jsx",
        "less",
        "lua",
        "php",
        "python",
        "r",
        "ruby",
        "rust",
        "scss",
        "sql",
        "swift",
        "typescript",
        "vb",
        "xml",
        "yaml",
        "yml",
        "zsh",
        "bash",
        "bat",
        "dockerfile",
        "groovy",
        "hcl",
      ],
    },
  },
});
